name: Debian 12

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-distros]

jobs:
  debian-12:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      distro: "docker.io/library/debian:12-slim"
      package_man: "apt"