name: Execute - Test Install FOG

on:
  repository_dispatch:
    types: [fog-install-test]

defaults:
  run:
    shell: bash

permissions: 
  contents: write

jobs:
  run-all-distros:
    runs-on: ubuntu-22.04
    steps:
      - name: Run all distros
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
          -d '{"event_type":"run-distros"}'

  # ubuntu-24-04:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Run Ubuntu 24.04
  #       run: |
  #         curl -L \
  #         -X POST \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
  #         -d '{"event_type":"run-distros"}'
  
  # debian-12:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Run Debian 12
  #       run: |
  #         curl -L \
  #         -X POST \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
  #         -d '{"event_type":"run-distros"}'
  
  # fedora-40:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Run Fedora 40
  #       run: |
  #         curl -L \
  #         -X POST \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
  #         -d '{"event_type":"run-distros"}'

  # check-status:
  #   needs: [ubuntu-22-04, ubuntu-24-04, debian-12, fedora-40]

  #   runs-on: ubuntu-22.04
    
  #   steps:
  #     - name: Set status badges
  #       if: always()
  #       run: |
