name: Execute - Test Install FOG

on:
  repository_dispatch:
    types: [fog-install-test]

defaults:
  run:
    shell: bash

permissions: 
  actions: write
  contents: write

jobs:
  run-all-distros:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Create calling function
      #   run: |
      #     function run_distro_test() {
            
      #     }

      - name: Run all distros
        run: |
          for fn in $(cd ./.github/workflows && ls distro_*); do
            echo "$fn"

            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$fn/dispatches" \
            -d '{"ref":"main"}'
          done


      # - name: Run all distros
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
      #     -d '{"event_type":"run-distros"}'
