name: Execute - Test Install FOG

on:
  repository_dispatch:
    types: [fog-install-test]

defaults:
  run:
    shell: bash

permissions: 
  contents: write

jobs:
  run-all-distros:
    runs-on: ubuntu-22.04
    steps:
      - name: Run all distros
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rluzuriaga/testing-distros/dispatches \
          -d '{"event_type":"run-distros"}'
