name: test hook

on:
  workflow_dispatch: 

jobs:
  fedora-40:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      distro: "quay.io/fedora/fedora-minimal:40"
      package_man: "apt"

  test-webhook:
    runs-on: ubuntu-22.04
    needs: fedora-40
    if: always()
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_TEST }}
          content: "Hey <@everyone>"
          title: Install tests
          status: ${{ needs.fedora-40.result }}
          color: 0xff0000
          description: "Just a test - Failing on purpose"
          url: "https://github.com/rluzuriaga/fogproject"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}