name: Fedora 40

on:
  workflow_dispatch:
  workflow_call:

jobs:
  fedora-40:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      distro: "quay.io/fedora/fedora-minimal:40"
      package_man: "apt"

  test-webhook:
    needs: fedora-40
    uses: sarisia/actions-status-discord@v1
    with:
      webhook: ${{ secrets.DISCORD_TEST }}
      content: "Hey <@everyone>"
      title: Install tests
      status: ${{ needs.check-all-tests-completed-successfully.result }}
      color: 0xff0000
      description: "Just a test - Failing on purpose"
      url: "https://github.com/rluzuriaga/fogproject"