name: Ubuntu 22.04

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-distros]

jobs:
  ubuntu-22-04:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      distro: "docker.io/library/ubuntu:22.04"
      package_man: "apt"